version: 2
jobs:
  build:
    working_directory: ~/yourdigiminder.com
    docker:
      - image: circleci/node:6.11.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: ./node_modules/.bin/nyc npm test
      - run:
          name: code-coverage
          command: 'npm test -- --coverage'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
